### ISSUE TITLE
Implementación de código fallida

### ISSUE THREAD

**Issue by YohaniIsaac** [enzozordan/p10hub12#1]
Hola, primero muchas gracias por tu código.

Intenté implementarlo en una matriz de Puntos P10 32x16, pero no se encienden todos los leds, modifiqué algo el código, pero aun así no lo logré, quisiera saber si tienes algún documento en el cual se basó para el código o algo similar con el fin de encontrar como hacer funcionar su código en mi matriz.

Estoy utilizando un esp32-S3, por lo que los pines utilizados no coinciden, puede que me falte inicializar una función interna o algo así.

Espero su respuesta, desde ya muchas gracias. Saludos!!

**Comment by enzozordan** [comment]
Hola el código debería funcionar sin modificaciones, pero está hecho para un ESP8266 tal como se especifica en los comentarios. Dada la simplicidad del código también debería funcionar en tu ESP32, pero hay que ver como conectaste los pines al panel. 
Podrías compartir tu conexionado?

**Comment by YohaniIsaac** [comment]
Muchas gracias por tu respuesta. 
Logré implementarlo correctamente, el problema se debía que, en mi caso, una de las pantallas que tenía, tuve fue necesario cambiar el sentido de CLK, SCLK y DATO.  Es decir, siempre estaban en alto, por lo que era un LOW, y luego volver a su estado natural HIGH, es decir, las señales siempre debían estar en alto.
Pero creo que depende del tipo de pantalla, porque luego hice lo mismo con la otra que tengo y tuve que volver al mismo código tuyo, ya que esta funcionaba con las salidas siempre en bajo.

Muchas gracias por tu código, me fue de mucha ayuda y pude aprender el funcionamiento de estas matrices de puntos. Saludos
